### ISSUE TITLE
`rolloverCounter` can get negative

### ISSUE THREAD

**Issue by wotzlaff** [shinyoshiaki/werift-webrtc#94]
I noticed that during some long-running stream I end up getting an exception which originates [here](https://github.com/shinyoshiaki/werift-webrtc/blob/develop/packages/rtp/src/srtp/context/context.ts#L151) because the value of `rolloverCounter` gets `-1` at some point.
Probably there is something wrong with the [update rule](https://github.com/shinyoshiaki/werift-webrtc/blob/develop/packages/rtp/src/srtp/context/context.ts#L133).

**Comment by shinyoshiaki** [comment]
Thank you for reporting the bug!

This bug was probably caused by the RTP packets being out of order when the sequenceNumber was rolled over for the first time.

I've released a version that fixes this bug. I've also added some simple test code for this bug.

e6d3e1a54ab7d32748c61222eb4018cdbb3c60d1

https://www.npmjs.com/package/werift/v/0.11.13

**Comment by wotzlaff** [comment]
Thank you again for quick fix. Hopefully, my description was good enough for you to find what's wrong.

I am closing this issue now because I am pretty sure, you know what you are doing ;)
